name: Build OpenWrt package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libssl-dev libncurses5-dev zlib1g-dev gawk git ccache gettext wget unzip python3

    - name: Prepare OpenWrt environment
      run: |
        git clone --depth 1 --branch master https://github.com/openwrt/openwrt.git /tmp/openwrt
        cd /tmp/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile package
      run: |
        cd /tmp/openwrt
        make tools/install
        make toolchain/install
        make package/libc/compile
        make package/libubus20210630/compile
        make package/libnettle8/compile
        make package/kmod-ipt-ipset/compile
        make package/libnetfilter-conntrack3/compile
        make package/dnsmasq_full/compile
        make package/index
